name: Output Issue
on: issue_commented
jobs:
  issue_commented:
    if: $ {{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: $ {{ github.event.issue.number }}